name: deploy_account
run-name: Deploy account for `${{ github.base_ref }}`
on:
  pull_request:
    types:
      - closed
    branches:
      - release/*/account

jobs:
  test:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Confirm
        run: |
          echo SHA=${{ github.event.pull_request.head.sha }}
          echo BRANCH=${{ github.base_ref }}
          git merge-base main ${{ github.base_ref }}
